apiVersion: v1
kind: PersistentVolume
metadata:
  name: ca-server-db  
  labels:
    type: local
spec:
  storageClassName: standard
  capacity:
    storage: 0.5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"